confdir = "/etc/confd/mysql"

[template]

src = "cluster.cnf.tmpl"

dest = "/etc/mysql/conf.d/cluster.cnf"

keys = [ "/components/galera" ]

owner = "root"
mode = "0554"

#reload_cmd = "/restart_mysql.sh"
